apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - secret.example.yaml
  - serviceaccount.yaml
  - job-migrate.yaml
  - deployment-api.yaml
  - service.yaml
  - poddisruptionbudget.yaml
  - networkpolicy.yaml
