# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from thinkback.rpc import memory_pb2 as memory__pb2

GRPC_GENERATED_VERSION = "1.69.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in memory_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class MemoryServiceStub(object):
    """─── Service ──────────────────────────────────────────────────────────────────"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Append = channel.unary_unary(
            "/memory.MemoryService/Append",
            request_serializer=memory__pb2.AppendRequest.SerializeToString,
            response_deserializer=memory__pb2.AppendResponse.FromString,
            _registered_method=True,
        )
        self.Recall = channel.unary_unary(
            "/memory.MemoryService/Recall",
            request_serializer=memory__pb2.RecallRequest.SerializeToString,
            response_deserializer=memory__pb2.RecallResponse.FromString,
            _registered_method=True,
        )
        self.Delete = channel.unary_unary(
            "/memory.MemoryService/Delete",
            request_serializer=memory__pb2.DeleteRequest.SerializeToString,
            response_deserializer=memory__pb2.DeleteResponse.FromString,
            _registered_method=True,
        )
        self.ListMemories = channel.unary_unary(
            "/memory.MemoryService/ListMemories",
            request_serializer=memory__pb2.ListMemoriesRequest.SerializeToString,
            response_deserializer=memory__pb2.ListMemoriesResponse.FromString,
            _registered_method=True,
        )
        self.GetMemory = channel.unary_unary(
            "/memory.MemoryService/GetMemory",
            request_serializer=memory__pb2.GetMemoryRequest.SerializeToString,
            response_deserializer=memory__pb2.GetMemoryResponse.FromString,
            _registered_method=True,
        )
        self.UpdateMemory = channel.unary_unary(
            "/memory.MemoryService/UpdateMemory",
            request_serializer=memory__pb2.UpdateMemoryRequest.SerializeToString,
            response_deserializer=memory__pb2.UpdateMemoryResponse.FromString,
            _registered_method=True,
        )
        self.Rebuild = channel.unary_unary(
            "/memory.MemoryService/Rebuild",
            request_serializer=memory__pb2.RebuildRequest.SerializeToString,
            response_deserializer=memory__pb2.RebuildResponse.FromString,
            _registered_method=True,
        )
        self.GetTask = channel.unary_unary(
            "/memory.MemoryService/GetTask",
            request_serializer=memory__pb2.GetTaskRequest.SerializeToString,
            response_deserializer=memory__pb2.TaskResponse.FromString,
            _registered_method=True,
        )
        self.GetL3BackgroundStatus = channel.unary_unary(
            "/memory.MemoryService/GetL3BackgroundStatus",
            request_serializer=memory__pb2.L3BackgroundStatusRequest.SerializeToString,
            response_deserializer=memory__pb2.L3BackgroundStatusResponse.FromString,
            _registered_method=True,
        )


class MemoryServiceServicer(object):
    """─── Service ──────────────────────────────────────────────────────────────────"""

    def Append(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Recall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListMemories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Rebuild(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetL3BackgroundStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Append": grpc.unary_unary_rpc_method_handler(
            servicer.Append,
            request_deserializer=memory__pb2.AppendRequest.FromString,
            response_serializer=memory__pb2.AppendResponse.SerializeToString,
        ),
        "Recall": grpc.unary_unary_rpc_method_handler(
            servicer.Recall,
            request_deserializer=memory__pb2.RecallRequest.FromString,
            response_serializer=memory__pb2.RecallResponse.SerializeToString,
        ),
        "Delete": grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=memory__pb2.DeleteRequest.FromString,
            response_serializer=memory__pb2.DeleteResponse.SerializeToString,
        ),
        "ListMemories": grpc.unary_unary_rpc_method_handler(
            servicer.ListMemories,
            request_deserializer=memory__pb2.ListMemoriesRequest.FromString,
            response_serializer=memory__pb2.ListMemoriesResponse.SerializeToString,
        ),
        "GetMemory": grpc.unary_unary_rpc_method_handler(
            servicer.GetMemory,
            request_deserializer=memory__pb2.GetMemoryRequest.FromString,
            response_serializer=memory__pb2.GetMemoryResponse.SerializeToString,
        ),
        "UpdateMemory": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateMemory,
            request_deserializer=memory__pb2.UpdateMemoryRequest.FromString,
            response_serializer=memory__pb2.UpdateMemoryResponse.SerializeToString,
        ),
        "Rebuild": grpc.unary_unary_rpc_method_handler(
            servicer.Rebuild,
            request_deserializer=memory__pb2.RebuildRequest.FromString,
            response_serializer=memory__pb2.RebuildResponse.SerializeToString,
        ),
        "GetTask": grpc.unary_unary_rpc_method_handler(
            servicer.GetTask,
            request_deserializer=memory__pb2.GetTaskRequest.FromString,
            response_serializer=memory__pb2.TaskResponse.SerializeToString,
        ),
        "GetL3BackgroundStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetL3BackgroundStatus,
            request_deserializer=memory__pb2.L3BackgroundStatusRequest.FromString,
            response_serializer=memory__pb2.L3BackgroundStatusResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "memory.MemoryService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("memory.MemoryService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class MemoryService(object):
    """─── Service ──────────────────────────────────────────────────────────────────"""

    @staticmethod
    def Append(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/memory.MemoryService/Append",
            memory__pb2.AppendRequest.SerializeToString,
            memory__pb2.AppendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Recall(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/memory.MemoryService/Recall",
            memory__pb2.RecallRequest.SerializeToString,
            memory__pb2.RecallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Delete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/memory.MemoryService/Delete",
            memory__pb2.DeleteRequest.SerializeToString,
            memory__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListMemories(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/memory.MemoryService/ListMemories",
            memory__pb2.ListMemoriesRequest.SerializeToString,
            memory__pb2.ListMemoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetMemory(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/memory.MemoryService/GetMemory",
            memory__pb2.GetMemoryRequest.SerializeToString,
            memory__pb2.GetMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateMemory(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/memory.MemoryService/UpdateMemory",
            memory__pb2.UpdateMemoryRequest.SerializeToString,
            memory__pb2.UpdateMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Rebuild(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/memory.MemoryService/Rebuild",
            memory__pb2.RebuildRequest.SerializeToString,
            memory__pb2.RebuildResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTask(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/memory.MemoryService/GetTask",
            memory__pb2.GetTaskRequest.SerializeToString,
            memory__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetL3BackgroundStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/memory.MemoryService/GetL3BackgroundStatus",
            memory__pb2.L3BackgroundStatusRequest.SerializeToString,
            memory__pb2.L3BackgroundStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
